# Generated by Django 5.2.10 on 2026-02-02 22:19

from django.db import migrations, models
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Post = apps.get_model('content_posts', 'Post')
    for post in Post.objects.all():
        if not post.title:
            base_slug = "post"
        else:
            base_slug = slugify(post.title)
            if not base_slug:
                base_slug = "post"
        
        slug = base_slug
        counter = 1
        while Post.objects.filter(slug=slug).exclude(pk=post.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        post.slug = slug
        post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('content_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
