# Generated by Django 5.2.10 on 2026-02-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_posts', '0003_remove_post_scheduled_date_post_engagement_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('platform', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('LinkedIn', 'LinkedIn')], max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('Published', 'Published')], default='Draft', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('engagement_score', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
