# Generated by Django 5.2.10 on 2026-02-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_posts', '0004_socialpost_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn')], max_length=50),
        ),
    ]
